import type { Content } from "./content.en";

/* French mirror of content.en.ts. TypeScript enforces identical structure. */

export const fr: Content = {
  common: {
    country: "Cameroun",
    mission:
      "Henri & Frères a pour vocation de rendre les produits de confiance du quotidien accessibles dans tout le Cameroun, grâce à un réseau de distribution national efficace bâti sur la fiabilité, le partenariat et le service.",
    allProducts: "Tous les produits",
    allNews: "Toute l'actualité",
    readMore: "Lire la suite",
    ourStory: "Notre histoire",
    whatWeDo: "Ce que nous faisons",
    learnMore: "En savoir plus",
    est: "Depuis",
    lines: "références",
    hub: "Hub",
    applyNow: "Postuler",
    startConversation: "Entamer la conversation",
    talkToTeam: "Parlez à notre équipe commerciale →",
  },

  home: {
    heroStats: [
      { label: "En activité depuis" },
      { label: "Pôles régionaux" },
      { label: "Employés" },
      { label: "Points de vente" },
    ],
    stats: { trusted: "La confiance pour distribuer les marques du quotidien au Cameroun" },
    intro: {
      eyebrow: "Qui nous sommes",
      title: "Trois décennies à acheminer les produits essentiels du quotidien au Cameroun.",
      body1:
        "Ce qui a commencé en 1993 comme une simple boutique à Yaoundé est aujourd'hui l'une des plateformes de distribution les plus fiables du pays. Nous relions les plus grands fabricants mondiaux aux rayons camerounais — en gérant l'importation, l'entreposage, la distribution et l'exécution en point de vente avec la rigueur d'une chaîne d'approvisionnement moderne.",
      body2:
        "Notre force, c'est la couverture. Du supermarché moderne au kiosque de quartier, nous rendons les produits de confiance disponibles partout où les Camerounais font leurs achats — de façon fiable et à l'échelle nationale.",
      statCaption: "Taux de service des commandes, sur 12 mois glissants",
    },
    categories: {
      eyebrow: "Ce que nous distribuons",
      titleLead: "Six catégories,",
      titleAccent: "un réseau de confiance.",
      intro:
        "Des produits d'épicerie aux soins personnels, nous distribuons les produits que les ménages utilisent chaque jour — dans le commerce moderne comme dans le commerce informel.",
    },
    coverage: {
      eyebrow: "Couverture nationale",
      title: "Un pays. Huit portes d'entrée régionales.",
      intro:
        "Nos pôles forment une colonne vertébrale logistique qui s'étend du port de Douala au corridor nord de Ngaoundéré — rapprochant les produits de confiance de chaque région que nous servons. Survolez une localité pour découvrir son rôle.",
      cta: "Découvrir notre logistique",
    },
    why: {
      eyebrow: "Pourquoi Henri & Frères",
      title: "Le partenaire de distribution qui inspire confiance aux marques.",
      intro:
        "Les fabricants nous choisissent parce que nous allions une couverture nationale à la rigueur opérationnelle d'une chaîne d'approvisionnement moderne.",
      imageAlt: "Flotte logistique dans un centre de distribution",
      reasons: [
        { title: "Un circuit de distribution inégalé", text: "Nous atteignons le commerce moderne, les grossistes et le commerce informel — les circuits où la majorité des Camerounais font réellement leurs achats." },
        { title: "La fiabilité à grande échelle", text: "Un taux de service supérieur à 99 % et une gestion rigoureuse des stocks sur lesquels fabricants et détaillants peuvent compter." },
        { title: "Un véritable réseau national", text: "Huit pôles régionaux et des centaines de points de livraison relient le port au dernier kilomètre." },
        { title: "Une connaissance du terrain", text: "Des données de sorties de caisse et d'analyse de couverture qui font de la distribution un moteur de croissance mesurable." },
      ],
    },
    timeline: {
      eyebrow: "Notre parcours",
      title: "D'une boutique à une plateforme nationale",
      intro: "Trois décennies de croissance régulière et réfléchie — bâtie agence après agence, partenariat après partenariat.",
      cta: "Lire notre histoire complète",
    },
    sectors: {
      eyebrow: "Les secteurs que nous servons",
      title: "Partout où le Cameroun s'approvisionne, nous livrons.",
      intro: "Un partenaire unique couvrant toute l'étendue du commerce — des chaînes de supermarchés nationales à la boutique de quartier.",
    },
    testimonials: { eyebrow: "En leurs mots" },
    news: { eyebrow: "Actualités", title: "Les dernières nouvelles de notre réseau" },
    cta: {
      eyebrow: "Développons votre couverture ensemble",
      title: "Prêt à rendre votre marque accessible à chaque Camerounais ?",
      intro:
        "Que vous soyez un fabricant international, un fournisseur régional ou un détaillant, notre équipe est prête à concevoir un circuit de distribution performant.",
    },
  },

  data: {
    stats: [
      { label: "Ans d'héritage commercial", sub: "Depuis 1993" },
      { label: "Pôles de distribution régionaux", sub: "Présence nationale" },
      { label: "Personnes employées", sub: "À travers le réseau" },
      { label: "Marques partenaires principales", sub: "Mondiales & régionales" },
      { label: "Points de vente servis", sub: "Commerce formel & informel" },
      { label: "Taux de service des commandes", sub: "Sur 12 mois glissants" },
    ],
    categories: [
      { name: "Alimentation", blurb: "Les produits de base qui structurent le foyer camerounais — pâtes, aides culinaires et essentiels de cuisine du quotidien.", items: ["Pâtes & semoule", "Bouillons & assaisonnements", "Tomate & sauces", "Huiles de cuisson", "Céréales & grains", "Conserves"] },
      { name: "Boissons", blurb: "Boissons chaudes et froides distribuées via le commerce moderne et traditionnel.", items: ["Boissons lactées en poudre", "Malt & boissons instantanées", "Jus & concentrés", "Eau", "Thé & infusions"] },
      { name: "Produits laitiers", blurb: "Produits laitiers et nutritionnels de longue conservation, plébiscités par les familles du pays.", items: ["Lait en poudre", "Lait évaporé", "Lait concentré", "Boissons nutritionnelles"] },
      { name: "Soins personnels", blurb: "Marques d'hygiène bucco-dentaire, de la peau et du corps présentes dans chaque région que nous servons.", items: ["Dentifrices & brosses", "Savons & gels douche", "Soins de la peau", "Déodorants", "Soins capillaires"] },
      { name: "Soins bébé", blurb: "Des produits doux et fiables pour les nourrissons et les jeunes enfants.", items: ["Nutrition infantile", "Couches", "Toilette bébé", "Lingettes"] },
      { name: "Entretien de la maison", blurb: "Produits d'entretien et de nettoyage qui font tourner foyers et entreprises.", items: ["Détergents", "Liquide vaisselle", "Nettoyants surfaces", "Désodorisants", "Insecticides"] },
      { name: "Papeterie", blurb: "Fournitures scolaires et de bureau — dont nos propres gammes de cahiers produites pour la rentrée.", items: ["Cahiers", "Cahiers d'exercices", "Stylos & crayons", "Papier bureautique", "Kits scolaires"] },
    ],
    brands: [
      { kind: "Partenaire principal", category: "Soins personnels & entretien", description: "Un partenariat de référence couvrant l'hygiène bucco-dentaire, le nettoyage de la peau et les produits d'entretien distribués à l'échelle nationale.", products: ["Nettoyage de la peau", "Entretien de la maison", "Hygiène bucco-dentaire"] },
      { kind: "Partenaire principal", category: "Hygiène bucco-dentaire", description: "Le leader de l'hygiène bucco-dentaire présent dans chaque région grâce à notre couverture du commerce moderne et traditionnel.", products: ["Dentifrice", "Brosses à dents", "Bain de bouche"] },
      { kind: "Partenaire principal", category: "Confiserie & pâtes à tartiner", description: "Chocolat et pâtes à tartiner camerounais emblématiques, acheminés de l'usine au rayon à l'échelle nationale.", products: ["Pâtes à tartiner chocolatées", "Confiserie", "Boissons cacaotées"] },
      { kind: "Partenaire principal", category: "Alimentation", description: "Pâtes et produits culinaires premium au service des ménages et de la restauration.", products: ["Pâtes", "Sauces", "Semoule"] },
      { kind: "Partenaire principal", category: "Alimentation & culinaire", description: "Des essentiels culinaires du quotidien fortement implantés dans le commerce informel.", products: ["Huile de cuisson", "Aides culinaires"] },
      { kind: "Partenaire principal", category: "Produits laitiers", description: "Marques de lait en poudre et évaporé de confiance, distribuées via notre chaîne laitière sèche et réfrigérée.", products: ["Lait en poudre", "Lait évaporé"] },
      { kind: "Partenaire principal", category: "Industrie alimentaire", description: "Partenaire industriel régional fournissant des produits alimentaires de base à notre réseau.", products: ["Produits meuniers", "Produits de base"] },
      { kind: "Partenaire principal", category: "Alimentation & boissons", description: "Une référence régionale distribuée dans nos dépôts et points de livraison.", products: ["Boissons", "Produits de base"] },
      { kind: "Partenaire principal", category: "Biens de consommation", description: "Des gammes de biens de consommation distribuées sur toute l'étendue de notre circuit de distribution.", products: ["Biens de consommation"] },
      { kind: "Marque propre", category: "Marque de distributeur", description: "Notre marque propre phare — une qualité fiable au quotidien à un prix accessible, pensée pour le consommateur camerounais.", products: ["Gammes d'entretien", "Produits alimentaires de base", "Papeterie"] },
      { kind: "Marque propre", category: "Produits laitiers & nutrition", description: "Notre propre marque de produits laitiers et nutritionnels, produite et distribuée selon les standards de qualité Henri & Frères.", products: ["Lait en poudre", "Boissons nutritionnelles"] },
    ],
    services: [
      { title: "Distribution nationale", desc: "Un circuit de distribution qui atteint le commerce moderne, les grossistes et le commerce informel dans chaque région où nous opérons.", points: ["Distribution primaire & secondaire", "Couverture commerce moderne & traditionnel", "Équipes dédiées grands comptes"] },
      { title: "Importation & sourcing", desc: "Gestion des importations et coordination douanière via la porte d'entrée de Douala, reliant les fabricants mondiaux aux rayons camerounais.", points: ["Coordination import & dédouanement", "Intégration des fournisseurs", "Conformité réglementaire"] },
      { title: "Entreposage & stockage", desc: "Des entrepôts régionaux avec stockage sec organisé, rotation des stocks et discipline d'inventaire pensés pour la vélocité des PGC.", points: ["Réseau d'entrepôts régionaux", "Rotation des stocks FEFO", "Contrôle des stocks en temps réel"] },
      { title: "Stratégie de mise sur le marché", desc: "Nous concevons et exécutons des plans de mise sur le marché qui placent les marques de nos partenaires à portée de main du consommateur.", points: ["Planification des territoires", "Optimisation de la couverture", "Activation commerciale"] },
      { title: "Exécution en point de vente & merchandising", desc: "Des équipes terrain qui assurent visibilité, disponibilité et part de linéaire dans des milliers de points de vente.", points: ["Merchandising & PLV", "Audits de disponibilité", "Exécution promotionnelle"] },
      { title: "Données & insights terrain", desc: "Des données de sorties de caisse et d'analyse de couverture qui donnent à nos partenaires une vision claire de la performance sur le terrain.", points: ["Reporting des sorties de caisse", "Analyse de couverture", "Appui à la planification de la demande"] },
    ],
    values: [
      { title: "Fiabilité", text: "Fabricants et détaillants s'organisent autour de nous parce que nous livrons — de façon constante et à grande échelle." },
      { title: "Partenariat", text: "Nous grandissons quand nos partenaires grandissent. Chaque relation se construit sur le long terme." },
      { title: "Intégrité", text: "Des pratiques transparentes et une gouvernance rigoureuse soutiennent trois décennies de confiance." },
      { title: "Service", text: "Du conseil d'administration au kiosque de quartier, nous traitons chaque client comme essentiel." },
      { title: "Excellence", text: "Nous nous imposons des standards dignes des plus grands fabricants mondiaux." },
      { title: "Les personnes", text: "Nos 300+ collaborateurs sont le réseau. Nous investissons dans leur développement et leur sécurité." },
    ],
    timeline: [
      { year: "1993", title: "Une première boutique ouvre", text: "Henri Tsakou Tiomela commence à commercialiser des biens de consommation depuis une modeste boutique à Yaoundé, sur la base de la confiance avec les détaillants locaux." },
      { year: "2004", title: "Henri & Frères est constituée", text: "L'entreprise familiale est officiellement constituée en Henri & Frères SARL, posant les bases d'une croissance structurée." },
      { year: "2005", title: "Porte d'entrée de Douala", text: "Une base dans le Littoral ouvre près du principal port du Cameroun, ancrant l'importation et la distribution primaire." },
      { year: "2008", title: "Expansion vers l'Ouest", text: "Un centre régional à Bafoussam étend la couverture aux hauts plateaux de l'Ouest, densément peuplés." },
      { year: "2011", title: "Atteindre l'Est", text: "Un pôle à Bertoua apporte un approvisionnement fiable aux régions de l'Est." },
      { year: "2016", title: "Porte d'entrée du Nord", text: "Ngaoundéré relie le corridor nord, complétant une présence véritablement nationale." },
      { year: "2020", title: "L'essor des marques propres", text: "Les marques Henri et Two Cows deviennent des références de confiance dans leurs catégories." },
      { year: "Aujourd'hui", title: "Une plateforme de distribution nationale", text: "Huit pôles régionaux, plus de 300 personnes et un réseau qui sert des dizaines de milliers de points de vente au Cameroun." },
    ],
    sectors: [
      "Supermarchés & commerce moderne",
      "Grossistes & distributeurs",
      "Commerce traditionnel & informel",
      "Hôtellerie, restauration & traiteurs",
      "Institutions & administrations",
      "Écoles & éducation",
    ],
    testimonials: [
      { quote: "Henri & Frères nous offrent une couverture que nous ne pourrions tout simplement pas bâtir seuls. Leur présence dans le commerce informel est sans égale au Cameroun.", name: "Directeur régional des ventes", role: "Fabricant PGC multinational" },
      { quote: "Fiables, rigoureux et transparents. Les stocks arrivent quand ils l'annoncent, ce qui est rare et précieux sur ce marché.", name: "Responsable de catégorie", role: "Groupe national de supermarchés" },
      { quote: "Un véritable partenaire, et non un simple fournisseur. Ils comprennent nos marques et les défendent en rayon.", name: "Directeur pays", role: "Groupe international de biens de consommation" },
    ],
    news: [
      { tag: "Logistique", title: "Henri & Frères étend sa capacité d'entreposage sur le corridor nord", excerpt: "De nouvelles capacités de stockage à Ngaoundéré renforcent l'approvisionnement des régions de l'Adamaoua, du Nord et de l'Extrême-Nord avant la haute saison." },
      { tag: "Marques propres", title: "Rentrée scolaire : les gammes de cahiers Henri montent en puissance pour la saison 2026", excerpt: "Notre gamme de papeterie propre s'étoffe pour répondre à la demande des écoles et des détaillants dans les huit pôles régionaux." },
      { tag: "Partenariats", title: "Renforcement de notre partenariat de distribution laitière", excerpt: "Un accord renouvelé étend la couverture nationale des marques de lait en poudre et évaporé de confiance." },
      { tag: "Opérations", title: "Le programme de modernisation de la flotte améliore la ponctualité des livraisons", excerpt: "L'investissement dans les véhicules de distribution secondaire porte notre taux de service glissant au-delà de 99 %." },
      { tag: "Ressources humaines", title: "Développement de notre programme femmes dans la distribution", excerpt: "Un engagement à ouvrir davantage de postes terrain et d'encadrement aux femmes dans tout le réseau." },
      { tag: "Logistique", title: "La modernisation de la porte d'entrée de Douala réduit les délais de dédouanement", excerpt: "Des améliorations à notre porte d'entrée import réduisent les délais entre le port et l'entrepôt régional." },
    ],
    jobs: [
      { title: "Responsable régional des ventes", location: "Douala", type: "Temps plein", team: "Commercial" },
      { title: "Superviseur des opérations d'entrepôt", location: "Yaoundé", type: "Temps plein", team: "Logistique" },
      { title: "Chargé de grands comptes", location: "Bafoussam", type: "Temps plein", team: "Commercial" },
      { title: "Coordinateur flotte & transport", location: "Ngaoundéré", type: "Temps plein", team: "Logistique" },
      { title: "Représentant merchandising terrain", location: "Bertoua", type: "Temps plein", team: "Force de vente" },
      { title: "Analyste planification de la demande", location: "Yaoundé", type: "Temps plein", team: "Chaîne d'approvisionnement" },
    ],
    csrPillars: [
      { title: "Opportunité économique", text: "Chaque circuit que nous ouvrons crée des moyens de subsistance — pour nos équipes et pour les dizaines de milliers de petits détaillants qui dépendent d'un approvisionnement fiable." },
      { title: "Personnes & sécurité", text: "Nous investissons dans la formation, le bien-être et la sécurité de nos 300+ collaborateurs, dans les entrepôts, la flotte et sur le terrain." },
      { title: "Communauté & éducation", text: "Grâce à des fournitures scolaires abordables et à des programmes de rentrée, nous contribuons à garder les salles de classe approvisionnées au Cameroun." },
      { title: "Opérations responsables", text: "Nous œuvrons à réduire le gaspillage, à optimiser les tournées de livraison et à diminuer l'empreinte de notre réseau de distribution." },
    ],
    branches: [
      { role: "Siège & entrepôt central", region: "Centre" },
      { role: "Porte d'entrée import & pôle logistique", region: "Littoral" },
      { role: "Centre de distribution régional", region: "Ouest" },
      { role: "Pôle de distribution de l'Est", region: "Est" },
      { role: "Dépôt des hauts plateaux", region: "Ouest" },
      { role: "Dépôt & point de livraison", region: "Ouest" },
      { role: "Pôle d'entrée du Nord", region: "Adamaoua" },
    ],
  },

  about: {
    breadcrumb: "Accueil / À propos",
    eyebrow: "À propos d'Henri & Frères",
    title: "Une entreprise de distribution bâtie sur la confiance.",
    intro: "Depuis plus de trois décennies, nous relions les fabricants au consommateur camerounais — en alliant couverture nationale et rigueur d'une chaîne d'approvisionnement moderne.",
    missionLabel: "Notre mission",
    visionLabel: "Notre vision",
    vision: "Être reconnu comme le partenaire de distribution le plus fiable et le plus performant du Cameroun — le réseau sur lequel les marques mondiales comptent pour atteindre chaque rayon et chaque consommateur du pays.",
    scaleEyebrow: "Notre envergure",
    scaleTitle: "Une croissance mesurée en couverture et en fiabilité",
    approachEyebrow: "Notre approche",
    approachTitle: "Des racines familiales, une discipline d'entreprise.",
    approach1: "Nous restons une entreprise d'origine familiale — et cet héritage transparaît dans notre manière de traiter partenaires, collaborateurs et clients. Mais notre façon d'opérer est résolument moderne : entreposage structuré, rotation rigoureuse des stocks, couverture pilotée par la donnée et une flotte conçue pour la vélocité.",
    approach2: "C'est cette combinaison qui a gagné la confiance de certains des plus grands fabricants mondiaux, et des milliers de détaillants qui comptent sur nous pour garnir leurs rayons.",
    valuesEyebrow: "Nos valeurs",
    valuesTitle: "Les principes derrière chaque livraison",
    valuesIntro: "Six engagements qui nous ont guidés d'une simple boutique à un réseau national.",
    leadershipEyebrow: "Direction",
    leadershipTitle: "Les personnes qui pilotent le réseau",
    leadershipIntro: "Des dirigeants expérimentés alliant héritage entrepreneurial et rigueur opérationnelle.",
    milestonesEyebrow: "Étapes clés",
    milestonesTitle: "Trois décennies de croissance réfléchie",
    leaders: [
      { role: "Fondateur", bio: "L'entrepreneur dont la confiance nouée avec les détaillants locaux en 1993 est devenue le socle d'une entreprise de distribution nationale." },
      { role: "Directeur général", bio: "Il pilote les opérations et la stratégie de croissance de l'entreprise, développant le réseau tout en préservant l'éthique de service qui l'a fondé." },
    ],
  },

  ourStory: {
    breadcrumb: "Accueil / Notre histoire",
    eyebrow: "Notre histoire · Depuis 1993",
    title: "Comment une simple boutique est devenue un réseau national.",
    intro: "Une histoire de confiance, de patience et de service sans relâche — racontée sur trois décennies de commerce camerounais.",
    s1Eyebrow: "1993 — Les débuts",
    s1Quote: "Tout a commencé comme la plupart des entreprises durables — avec une personne, une boutique, et une réputation valant plus que n'importe quel bilan.",
    s1Body: "En 1993, Henri Tsakou Tiomela a ouvert une modeste boutique à Yaoundé, commercialisant les produits du quotidien dont dépendent les familles camerounaises. Ce qui distinguait l'entreprise, ce n'était pas sa taille mais sa fiabilité. Les détaillants savaient que ce qu'Henri promettait, Henri le livrait. Cette confiance s'est cumulée — commande après commande, saison après saison.",
    imageAlt: "Marché et commerce camerounais",
    s2Eyebrow: "2004 — Une entreprise prend forme",
    s2Title: "Du commerçant au distributeur.",
    s2Body: "En 2004, la demande avait dépassé la boutique. L'entreprise a été officiellement constituée en Henri & Frères SARL, et avec la structure est venue l'ambition. Une base près du port de Douala a ouvert la voie à l'importation et à la distribution primaire — et l'entreprise a commencé à bâtir la présence régionale qui la définit aujourd'hui.",
    s2Stats: [
      { label: "Début de l'activité" },
      { label: "Constitution" },
      { label: "Pôles régionaux aujourd'hui" },
      { label: "Collaborateurs" },
    ],
    s3Eyebrow: "Aujourd'hui — Au cœur du quotidien",
    s3Body1: "Trente ans plus tard, Henri & Frères achemine les marques qui font le quotidien du Cameroun — des noms mondiaux comme Unilever et Colgate à nos propres marques Henri et Two Cows. Nous employons plus de 300 personnes, exploitons huit portes d'entrée régionales et servons des dizaines de milliers de points de vente, du supermarché moderne au kiosque de quartier.",
    s3Body2: "La boutique est devenue un réseau. Mais le principe qui l'a bâti — tenir sa promesse, à chaque fois — n'a jamais changé.",
  },

  products: {
    breadcrumb: "Accueil / Produits",
    eyebrow: "Notre portefeuille",
    title: "Des produits du quotidien, livrés dans tout le pays.",
    intro: "Sept catégories couvrant les essentiels dont dépendent ménages et entreprises du Cameroun — issus de grands fabricants et de nos propres marques de confiance.",
    browseEyebrow: "Parcourir la gamme",
    browseTitle: "Un portefeuille pensé autour du panier camerounais",
    browseIntro: "Filtrez par catégorie pour explorer des références représentatives. Notre assortiment complet couvre des centaines de références dans le commerce moderne et traditionnel.",
    byCategoryEyebrow: "Par catégorie",
    byCategoryTitle: "Sept catégories, une seule chaîne d'approvisionnement",
    note: "Vous cherchez une marque ou une référence précise ?",
  },

  brands: {
    breadcrumb: "Accueil / Marques",
    eyebrow: "Les marques que nous représentons",
    title: "Les marques auxquelles le Cameroun fait confiance — portées par le réseau qui les distribue.",
    intro: "Nous sommes le partenaire de distribution privilégié des fabricants mondiaux comme des leaders régionaux, et le fier propriétaire de deux marques locales de confiance.",
    ownedEyebrow: "Nos marques propres",
    ownedTitle: "Conçues pour le Cameroun, par Henri & Frères",
    ownedIntro: "Au-delà de la distribution, nous bâtissons nos propres marques — une qualité fiable à un prix adapté au consommateur camerounais.",
    distributedNote: "Distribuées dans les huit pôles régionaux",
    partnersEyebrow: "Partenaires principaux",
    partnersTitle: "La confiance des plus grands fabricants mondiaux",
    partnersIntro: "Un portefeuille de partenariats couvrant l'alimentation, les soins personnels, les produits laitiers et l'entretien — distribués avec la rigueur qu'exige chaque marque.",
  },

  distribution: {
    breadcrumb: "Accueil / Distribution",
    eyebrow: "Distribution & logistique",
    title: "La colonne vertébrale du commerce camerounais.",
    intro: "Du port de Douala au corridor nord, notre réseau achemine les produits avec la rapidité, la rigueur et la portée qu'exigent les PGC.",
    capacity: [
      { label: "Pôles de distribution régionaux" },
      { label: "Points de vente atteints" },
      { label: "Régions couvertes" },
      { label: "Taux de service des commandes" },
    ],
    mapEyebrow: "Carte du réseau",
    mapTitle: "Huit portes d'entrée, une couverture complète.",
    mapIntro: "Chaque pôle est positionné pour servir efficacement sa région — réduisant les délais, protégeant la disponibilité des stocks et rapprochant les produits de confiance du consommateur.",
    howEyebrow: "Comment ça marche",
    howTitle: "Une chaîne d'approvisionnement conçue pour la vélocité",
    howIntro: "Quatre étapes rigoureuses acheminent un produit du port au panier du consommateur — de façon fiable et à grande échelle.",
    chain: [
      { title: "Import & sourcing", text: "Les marchandises arrivent par la porte d'entrée de Douala, dédouanées et consolidées pour la distribution." },
      { title: "Entreposage régional", text: "Les stocks sont réceptionnés dans des entrepôts régionaux avec une rotation FEFO rigoureuse et un contrôle des stocks." },
      { title: "Livraison primaire & secondaire", text: "Une flotte moderne achemine les produits du pôle au dépôt puis au point de vente, sur des tournées planifiées." },
      { title: "Exécution en point de vente", text: "Les équipes terrain assurent la disponibilité et la visibilité dans le commerce moderne et traditionnel." },
    ],
    fleetEyebrow: "Flotte & entreposage",
    fleetTitle: "Conçu pour suivre le rythme de la demande.",
    fleetBody: "Nos entrepôts régionaux et notre flotte de livraison moderne forment un système intégré — conçu pour garder les rayons pleins et les délais courts, même dans les saisons les plus exigeantes. L'investissement continu dans les véhicules et la capacité de stockage maintient notre taux de service au-delà de 99 %.",
    fleetMetrics: [
      { label: "Taux de service" },
      { label: "Entrepôts" },
      { label: "Réapprovisionnement type" },
    ],
  },

  services: {
    breadcrumb: "Accueil / Services",
    eyebrow: "Ce que nous faisons",
    title: "Une distribution de bout en bout, menée avec rigueur.",
    intro: "Du port au point de vente, nous gérons chaque maillon de la chaîne — pour que nos partenaires se concentrent sur leurs marques pendant que nous développons leur couverture.",
    propEyebrow: "Pour nos partenaires",
    propTitle: "Un seul partenaire. Une couverture totale du marché.",
    propBody: "Choisir Henri & Frères, c'est disposer d'un accès unique et responsable à l'ensemble du marché camerounais. Nous gérons importation, stockage, distribution et exécution comme un service intégré — appuyé par les données dont vous avez besoin pour piloter la performance.",
    propImageAlt: "Équipe commerciale analysant les données de distribution",
    propBullets: [
      "Une couverture nationale en un seul accord",
      "Commerce moderne & traditionnel",
      "Reporting transparent des sorties de caisse",
      "Équipes dédiées grands comptes",
    ],
  },

  partners: {
    breadcrumb: "Accueil / Partenaires",
    eyebrow: "Partenariats",
    title: "Grandissez avec le réseau en qui le marché a confiance.",
    intro: "Nous bâtissons des partenariats de long terme qui font de la distribution un moteur de croissance mesurable — pour les noms mondiaux comme pour les marques locales.",
    logosNote: "Un portefeuille de partenaires de confiance",
    whoEyebrow: "Avec qui nous travaillons",
    whoTitle: "Conçu pour chaque type de partenaire",
    whoIntro: "Quel que soit votre point de départ, nous concevons un circuit de distribution adapté à votre marque et à vos ambitions.",
    types: [
      { title: "Fabricants multinationaux", text: "Un accès clé en main au marché camerounais avec la couverture, la conformité et le reporting attendus des marques mondiales." },
      { title: "Fournisseurs régionaux", text: "Un accès à la distribution nationale et à l'exécution en point de vente qu'il faudrait des années à bâtir seul." },
      { title: "Détaillants & grossistes", text: "Un approvisionnement fiable en marques de confiance, à temps et complet, dans chaque catégorie que nous distribuons." },
      { title: "Institutions & administrations", text: "Un approvisionnement et une distribution en volume fiables pour les organisations opérant à grande échelle." },
    ],
    commitEyebrow: "Notre engagement",
    commitTitle: "Ce sur quoi chaque partenaire peut compter.",
    commitBody: "Un partenariat avec Henri & Frères est un engagement de standards. Voici ce que nous apportons dès le premier jour.",
    promises: [
      "Une couverture nationale du commerce moderne et traditionnel",
      "Un reporting de performance transparent et piloté par la donnée",
      "Un entreposage et une gestion des stocks rigoureux",
      "Des équipes commerciales et grands comptes dédiées",
      "Une expertise en conformité et dédouanement à la porte de Douala",
      "Trois décennies de crédibilité sur le marché",
    ],
  },

  news: {
    breadcrumb: "Accueil / Actualités",
    eyebrow: "Actualités",
    title: "Actualités & analyses de notre réseau.",
    intro: "Annonces, étapes clés et points de vue de l'ensemble de notre activité de distribution nationale.",
    featured: "À la une",
    readStory: "Lire l'article",
    all: "Tout",
  },

  careers: {
    breadcrumb: "Accueil / Carrières",
    eyebrow: "Carrières",
    title: "Construisez votre carrière là où le pays se met en mouvement.",
    intro: "Rejoignez plus de 300 collaborateurs qui garnissent les rayons du Cameroun — et évoluez avec l'une des entreprises de distribution les plus fiables du pays.",
    cultureEyebrow: "La vie chez Henri & Frères",
    cultureTitle: "Les personnes sont le réseau.",
    cultureBody: "Derrière chaque livraison, il y a une personne qui l'a rendue possible — dans l'entrepôt, sur la route, sur le terrain et au siège. Nous investissons dans nos équipes parce qu'elles sont la raison de la confiance des détaillants et des fabricants.",
    cultureStats: [
      { label: "Collaborateurs" },
      { label: "Sites" },
      { label: "Ans" },
    ],
    imageAlt: "L'équipe Henri & Frères au travail",
    benefitsEyebrow: "Pourquoi nous rejoindre",
    benefitsTitle: "Ce que nous offrons",
    benefits: [
      { title: "Une réelle progression", text: "Une entreprise dynamique où les personnes capables prennent des responsabilités tôt et évoluent avec le réseau." },
      { title: "Formation & développement", text: "Formation sur le terrain et mentorat dans le commercial, la logistique et les opérations." },
      { title: "Une équipe qui vous soutient", text: "Une culture collaborative fondée sur le respect, le service et la réussite partagée." },
      { title: "Stabilité & sécurité", text: "La sécurité d'une entreprise établie qui investit dans le bien-être de ses équipes." },
    ],
    rolesEyebrow: "Postes ouverts",
    rolesTitle: "Opportunités actuelles",
    rolesIntro: "Une sélection de postes que nous recrutons dans tout le réseau. Vous ne trouvez pas le poste idéal ? Envoyez-nous une candidature spontanée ci-dessous.",
    applyEyebrow: "Postuler",
    applyTitle: "Rejoignez l'équipe",
    applyIntro: "Remplissez le formulaire et joignez votre CV. Nous étudions chaque candidature.",
  },

  csr: {
    breadcrumb: "Accueil / Durabilité",
    eyebrow: "Durabilité & impact",
    title: "Une distribution qui fait grandir les communautés.",
    intro: "Notre réseau ne fait pas que déplacer des produits — il crée des moyens de subsistance, garnit les rayons et les salles de classe, et relie les communautés aux essentiels dont elles dépendent.",
    commitEyebrow: "Notre engagement",
    commitTitle: "La valeur partagée, par principe.",
    commit1: "Un réseau de distribution touche des milliers de vies. Chaque circuit que nous ouvrons soutient un petit détaillant ; chaque entrepôt que nous exploitons emploie une communauté ; chaque rentrée scolaire, nous aidons les enfants à poursuivre leur apprentissage. Nous prenons cette responsabilité au sérieux.",
    commit2: "Notre approche est concrète et ancrée dans le réel — centrée sur les domaines où une entreprise de distribution peut faire une différence réelle et mesurable.",
    imageAlt: "Communauté et commerce local au Cameroun",
    focusEyebrow: "Nos axes prioritaires",
    focusTitle: "Quatre engagements qui guident notre impact",
    impactEyebrow: "Notre empreinte",
    impactTitle: "Un impact mesurable",
    impact: [
      { label: "Détaillants soutenus par un approvisionnement fiable" },
      { label: "Emplois directs dans le réseau" },
      { label: "Communautés régionales où nous opérons" },
    ],
    quote: "Un pays fonctionne grâce à ses produits essentiels du quotidien. Les rendre disponibles de façon fiable — partout, pour tous — est notre contribution au progrès du Cameroun.",
    quoteBy: "La direction d'Henri & Frères",
  },

  contact: {
    breadcrumb: "Accueil / Contact",
    eyebrow: "Contact",
    title: "Parlons distribution.",
    intro: "Que vous soyez un fabricant en quête de couverture nationale, un détaillant passant commande ou un candidat explorant une carrière — notre équipe est prête à vous aider.",
    details: [
      { label: "Siège social" },
      { label: "Téléphone" },
      { label: "E-mail" },
      { label: "Horaires" },
    ],
    hoursValue: "Lun–Sam, 8h00 – 18h00 WAT",
    whatsappTitle: "Discuter sur WhatsApp",
    whatsappSub: "Le moyen le plus rapide de joindre notre équipe.",
    mapTitle: "Siège d'Henri & Frères — Yaoundé",
    locationsTitle: "Nos sites",
    locationsIntro: "Huit portes d'entrée régionales nous gardent proches de nos partenaires et clients partout au Cameroun.",
  },

  forms: {
    application: {
      name: "Nom complet", namePh: "Votre nom",
      email: "E-mail", emailPh: "vous@email.com",
      phone: "Téléphone",
      role: "Poste", rolePh: "Sélectionnez un poste…", roleGeneral: "Candidature spontanée",
      message: "Pourquoi Henri & Frères ?", messagePh: "Parlez-nous brièvement de votre expérience et de votre motivation.",
      cv: "CV", cvPh: "Téléversez votre CV (PDF, DOCX — max 5 Mo)",
      consent: "J'accepte que Henri & Frères conserve mes informations à des fins de recrutement.",
      submit: "Envoyer ma candidature", submitting: "Envoi…",
      doneTitle: "Candidature reçue",
      doneBody: "Merci de votre intérêt pour Henri & Frères. Notre équipe RH étudie chaque candidature et vous contactera si votre profil correspond à un poste.",
      another: "Envoyer une autre candidature",
    },
    contact: {
      name: "Nom complet", namePh: "Votre nom",
      company: "Société", companyPh: "Société (facultatif)",
      email: "E-mail", emailPh: "vous@email.com",
      phone: "Téléphone",
      type: "Comment pouvons-nous aider ?", typePh: "Sélectionnez un type de demande…",
      message: "Message", messagePh: "Parlez-nous un peu de votre demande…",
      consent: "J'accepte d'être contacté au sujet de ma demande et j'accepte la politique de confidentialité.",
      submit: "Envoyer le message", submitting: "Envoi…",
      doneTitle: "Message envoyé",
      doneBody: "Merci de nous avoir contactés. Un membre de notre équipe vous répondra sous un jour ouvré.",
      another: "Envoyer un autre message",
      inquiries: [
        "Devenir partenaire de distribution",
        "Demande fournisseur / fabricant",
        "Commande détaillant / grossiste",
        "Carrières",
        "Médias & presse",
        "Demande générale",
      ],
    },
  },

  companyProfile: {
    docLabel: "Document institutionnel",
    subtitle: "Profil de l'entreprise · L'épine dorsale de la distribution au Cameroun",
    print: "Télécharger / Imprimer en PDF",
    overview: "Présentation",
    overviewBody:
      "Henri & Frères SARL est l'une des principales entreprises de distribution et d'importation de PGC au Cameroun. D'une simple boutique ouverte à Yaoundé en 1993, l'entreprise est devenue une plateforme de distribution nationale qui sert des dizaines de milliers de points de vente à travers le pays.",
    keyFacts: "Chiffres clés",
    facts: [
      { label: "Raison sociale", value: "Henri & Frères SARL" },
      { label: "Fondée", value: "1993 (activité) · 2004 (constitution)" },
      { label: "Siège", value: "Yaoundé, Cameroun" },
      { label: "Fondateur", value: "Henri Tsakou Tiomela" },
      { label: "Directeur général", value: "André Tsapi" },
      { label: "Employés", value: "300+" },
      { label: "Secteur", value: "Distribution en gros & importation de PGC" },
      { label: "Pôles régionaux", value: "8 (Yaoundé, Douala, Bafoussam, Bertoua, Dschang, Mbouda, Ngaoundéré + points)" },
    ],
    atGlance: "En bref",
    brandsTitle: "Marques distribuées",
    principalLabel: "Partenaires principaux :",
    ownedLabel: "Marques propres :",
    categoriesTitle: "Catégories de produits",
    networkTitle: "Réseau de distribution",
    contactTitle: "Contact",
    rights: "Tous droits réservés.",
  },

  notFound: {
    title: "Cette adresse ne figure pas sur notre carte.",
    body: "La page que vous cherchez a peut-être été déplacée. Retrouvons un terrain connu.",
    home: "Retour à l'accueil",
    contact: "Nous contacter",
  },
};
