/* =========================================================================
   English content — single source of truth for the site's copy shape.
   content.fr.ts must mirror this exact structure (enforced by TypeScript).
   Purely structural/numeric config (icons, images, coords, numbers) stays
   in data.ts and is merged by index/slug at render time.
   ========================================================================= */

export const en = {
  common: {
    country: "Cameroon",
    mission:
      "Henri & Frères exists to make trusted everyday products accessible across Cameroon through an efficient nationwide distribution network built on reliability, partnership and service.",
    allProducts: "All products",
    allNews: "All news",
    readMore: "Read more",
    ourStory: "Our story",
    whatWeDo: "What we do",
    learnMore: "Learn more",
    est: "Est.",
    lines: "lines",
    hub: "Hub",
    applyNow: "Apply now",
    startConversation: "Start a conversation",
    talkToTeam: "Talk to our commercial team →",
  },

  home: {
    heroStats: [
      { label: "Trading since" },
      { label: "Regional hubs" },
      { label: "Employees" },
      { label: "Outlets served" },
    ],
    stats: { trusted: "Trusted to distribute the brands Cameroon lives with" },
    intro: {
      eyebrow: "Who we are",
      title: "Three decades moving Cameroon’s everyday essentials.",
      body1:
        "What began in 1993 as a single Yaoundé storefront is today one of the country’s most dependable distribution platforms. We connect the world’s leading manufacturers to Cameroonian shelves — managing importation, warehousing, route-to-market and retail execution with the discipline of a modern supply-chain business.",
      body2:
        "Our advantage is reach. From modern supermarkets to the roadside kiosk, we make trusted products available wherever Cameroonians shop — reliably, and at national scale.",
      statCaption: "On-time order fulfilment, rolling 12 months",
    },
    categories: {
      eyebrow: "What we distribute",
      titleLead: "Six categories,",
      titleAccent: "one trusted network.",
      intro:
        "From pantry staples to personal care, we carry the products households reach for every day — across modern retail and the informal trade alike.",
    },
    coverage: {
      eyebrow: "National coverage",
      title: "One country. Eight regional gateways.",
      intro:
        "Our hubs form a supply spine that runs from the Douala port to the northern corridor at Ngaoundéré — putting trusted products within reach of every region we serve. Hover a location to explore its role.",
      cta: "Inside our logistics",
    },
    why: {
      eyebrow: "Why Henri & Frères",
      title: "The distribution partner brands trust.",
      intro:
        "Manufacturers choose us because we combine national reach with the operational discipline of a modern supply-chain company.",
      imageAlt: "Logistics fleet at a distribution centre",
      reasons: [
        { title: "Unmatched route-to-market", text: "We reach modern retail, wholesalers and the informal trade — the channels where most of Cameroon actually shops." },
        { title: "Reliability at scale", text: "A 99%+ fulfilment rate and disciplined stock management principals and retailers can plan around." },
        { title: "A true national network", text: "Eight regional hubs and hundreds of delivery points connect the port to the last mile." },
        { title: "Insight on the ground", text: "Sell-out data and coverage analytics that turn distribution into a measurable growth engine." },
      ],
    },
    timeline: {
      eyebrow: "Our journey",
      title: "From one storefront to a national platform",
      intro: "Three decades of steady, deliberate growth — built branch by branch, partnership by partnership.",
      cta: "Read our full story",
    },
    sectors: {
      eyebrow: "Sectors we serve",
      title: "Wherever Cameroon shops, we deliver.",
      intro: "A single partner spanning the full breadth of the trade — from national supermarket chains to the neighbourhood boutique.",
    },
    testimonials: { eyebrow: "In their words" },
    news: { eyebrow: "Newsroom", title: "The latest from our network" },
    cta: {
      eyebrow: "Let’s build reach together",
      title: "Ready to put your brand within reach of every Cameroonian?",
      intro:
        "Whether you’re a global manufacturer, a regional supplier or a retailer, our team is ready to design a route-to-market that performs.",
    },
  },

  // Arrays below align by index with the structural arrays in data.ts.
  data: {
    stats: [
      { label: "Years of trading heritage", sub: "Since 1993" },
      { label: "Regional distribution hubs", sub: "Nationwide footprint" },
      { label: "People employed", sub: "Across the network" },
      { label: "Principal brand partners", sub: "Global & regional" },
      { label: "Retail outlets served", sub: "Formal & informal trade" },
      { label: "Order fulfilment rate", sub: "Rolling 12 months" },
    ],
    categories: [
      { name: "Food", blurb: "Pantry staples that anchor the Cameroonian household — pasta, culinary aids and everyday cooking essentials.", items: ["Pasta & semolina", "Bouillons & seasoning", "Tomato & sauces", "Cooking oils", "Cereals & grains", "Canned goods"] },
      { name: "Beverages", blurb: "Hot and cold drinks distributed through both modern and traditional trade channels.", items: ["Powdered milk drinks", "Malt & instant beverages", "Juices & concentrates", "Water", "Tea & infusions"] },
      { name: "Dairy", blurb: "Shelf-stable dairy and nutrition brands trusted by families across the country.", items: ["Powdered milk", "Evaporated milk", "Condensed milk", "Nutritional drinks"] },
      { name: "Personal Care", blurb: "Oral, skin and hygiene brands that reach shelves in every region we serve.", items: ["Toothpaste & brushes", "Soaps & body wash", "Skin care", "Deodorants", "Hair care"] },
      { name: "Baby Care", blurb: "Gentle, dependable products for infants and young children.", items: ["Infant nutrition", "Diapers", "Baby toiletries", "Wipes"] },
      { name: "Household", blurb: "Cleaning and home-care lines that keep homes and businesses running.", items: ["Detergents", "Dishwashing", "Surface cleaners", "Air care", "Insecticides"] },
      { name: "Stationery", blurb: "School and office supplies — including our own notebook lines produced for the back-to-school season.", items: ["Notebooks", "Exercise books", "Pens & pencils", "Office paper", "School kits"] },
    ],
    brands: [
      { kind: "Principal partner", category: "Personal & Home Care", description: "A cornerstone partnership spanning oral care, skin cleansing and home-care lines distributed nationwide.", products: ["Skin cleansing", "Home care", "Oral care"] },
      { kind: "Principal partner", category: "Oral Care", description: "Oral-care leadership brought to every region through our modern and traditional trade coverage.", products: ["Toothpaste", "Toothbrushes", "Mouthwash"] },
      { kind: "Principal partner", category: "Confectionery & Spreads", description: "Iconic Cameroonian chocolate and spreads, moved from factory to shelf at national scale.", products: ["Chocolate spreads", "Confectionery", "Cocoa drinks"] },
      { kind: "Principal partner", category: "Food", description: "Premium pasta and culinary products serving households and food-service customers.", products: ["Pasta", "Sauces", "Semolina"] },
      { kind: "Principal partner", category: "Food & Culinary", description: "Everyday culinary staples with deep penetration across the informal trade.", products: ["Cooking oil", "Culinary aids"] },
      { kind: "Principal partner", category: "Dairy", description: "Trusted powdered and evaporated milk brands distributed through our dairy cold and dry chain.", products: ["Powdered milk", "Evaporated milk"] },
      { kind: "Principal partner", category: "Food Manufacturing", description: "Regional manufacturing partner supplying staple food lines into our network.", products: ["Milled products", "Staples"] },
      { kind: "Principal partner", category: "Food & Beverage", description: "A regional favourite carried across our depots and delivery points.", products: ["Beverages", "Food staples"] },
      { kind: "Principal partner", category: "Consumer Goods", description: "Consumer-goods lines distributed through the full breadth of our route-to-market.", products: ["Consumer goods"] },
      { kind: "Owned brand", category: "Private Label", description: "Our flagship own-brand — dependable everyday quality at an accessible price, built for the Cameroonian shopper.", products: ["Household lines", "Food staples", "Stationery"] },
      { kind: "Owned brand", category: "Dairy & Nutrition", description: "Our own dairy and nutrition label, produced and distributed under Henri & Frères quality standards.", products: ["Powdered milk", "Nutritional drinks"] },
    ],
    services: [
      { title: "Nationwide Distribution", desc: "A route-to-market that reaches modern retail, wholesalers and the informal trade in every region we operate.", points: ["Primary & secondary distribution", "Modern & traditional trade coverage", "Dedicated key-account teams"] },
      { title: "Importation & Sourcing", desc: "Import handling and customs coordination through the Douala gateway, connecting global manufacturers to Cameroonian shelves.", points: ["Import & clearing coordination", "Supplier onboarding", "Regulatory compliance"] },
      { title: "Warehousing & Storage", desc: "Regional warehouses with organised dry storage, stock rotation and inventory discipline built for FMCG velocity.", points: ["Regional warehouse footprint", "FEFO stock rotation", "Real-time inventory control"] },
      { title: "Route-to-Market Strategy", desc: "We design and execute go-to-market plans that put principals’ brands within arm’s reach of the consumer.", points: ["Territory planning", "Coverage optimisation", "Trade activation"] },
      { title: "Retail Execution & Merchandising", desc: "Field teams that secure visibility, availability and share of shelf across thousands of outlets.", points: ["Merchandising & POS", "Availability audits", "Promotional execution"] },
      { title: "Data & Trade Insights", desc: "Sell-out data and coverage analytics that give principals a clear view of performance on the ground.", points: ["Sell-out reporting", "Coverage analytics", "Demand planning support"] },
    ],
    values: [
      { title: "Reliability", text: "Principals and retailers plan around us because we deliver — consistently, and at scale." },
      { title: "Partnership", text: "We grow when our partners grow. Every relationship is built for the long term." },
      { title: "Integrity", text: "Transparent dealing and disciplined governance underpin three decades of trust." },
      { title: "Service", text: "From the boardroom to the roadside kiosk, we treat every customer as essential." },
      { title: "Excellence", text: "We hold ourselves to standards worthy of the world’s leading manufacturers." },
      { title: "People", text: "Our 300+ colleagues are the network. We invest in their growth and safety." },
    ],
    timeline: [
      { year: "1993", title: "A single shop opens", text: "Henri Tsakou Tiomela begins trading consumer goods from a modest storefront in Yaoundé, built on trust with local retailers." },
      { year: "2004", title: "Henri & Frères is incorporated", text: "The family trading business is formalised as Henri & Frères SARL, laying the foundation for structured growth." },
      { year: "2005", title: "Douala gateway", text: "A Littoral base opens near Cameroon’s principal port, anchoring importation and primary distribution." },
      { year: "2008", title: "Expansion into the West", text: "A regional centre in Bafoussam extends coverage into the densely populated western highlands." },
      { year: "2011", title: "Reaching the East", text: "A hub in Bertoua brings dependable supply to the eastern regions." },
      { year: "2016", title: "Northern gateway", text: "Ngaoundéré connects the northern corridor, completing a truly national footprint." },
      { year: "2020", title: "Own brands scale", text: "The Henri and Two Cows private labels grow into trusted household names in their categories." },
      { year: "Today", title: "A national distribution platform", text: "Eight regional hubs, 300+ people and a network serving tens of thousands of outlets across Cameroon." },
    ],
    sectors: [
      "Supermarkets & Modern Retail",
      "Wholesalers & Distributors",
      "Traditional & Informal Trade",
      "Hotels, Restaurants & Catering",
      "Institutions & Government",
      "Schools & Education",
    ],
    testimonials: [
      { quote: "Henri & Frères give us reach we simply could not build alone. Their coverage of the informal trade is second to none in Cameroon.", name: "Regional Sales Director", role: "Multinational FMCG principal" },
      { quote: "Reliable, disciplined and transparent. Stock arrives when they say it will, which is rare and invaluable in this market.", name: "Category Manager", role: "National supermarket group" },
      { quote: "A genuine partner rather than a vendor. They understand our brands and defend them on the shelf.", name: "Country Manager", role: "Global consumer-goods company" },
    ],
    news: [
      { tag: "Logistics", title: "Henri & Frères expands warehousing capacity on the northern corridor", excerpt: "New storage capacity in Ngaoundéré strengthens supply to the Adamawa, North and Far North regions ahead of peak season." },
      { tag: "Own Brands", title: "Back-to-school: Henri notebook lines scale for the 2026 season", excerpt: "Our owned stationery range grows to meet demand from schools and retailers across all eight regional hubs." },
      { tag: "Partnerships", title: "Deepening our dairy distribution partnership", excerpt: "A renewed agreement extends nationwide coverage for trusted powdered and evaporated milk brands." },
      { tag: "Operations", title: "Fleet modernisation programme improves on-time delivery", excerpt: "Investment in secondary distribution vehicles lifts our rolling order-fulfilment rate above 99%." },
      { tag: "People", title: "Growing our women-in-distribution programme", excerpt: "A commitment to opening more field and management roles to women across the network." },
      { tag: "Logistics", title: "Douala gateway upgrade cuts clearance times", excerpt: "Improvements at our import gateway reduce lead times from port to regional warehouse." },
    ],
    jobs: [
      { title: "Regional Sales Manager", location: "Douala", type: "Full-time", team: "Commercial" },
      { title: "Warehouse Operations Supervisor", location: "Yaoundé", type: "Full-time", team: "Logistics" },
      { title: "Key Account Executive", location: "Bafoussam", type: "Full-time", team: "Commercial" },
      { title: "Fleet & Transport Coordinator", location: "Ngaoundéré", type: "Full-time", team: "Logistics" },
      { title: "Merchandising Field Representative", location: "Bertoua", type: "Full-time", team: "Field Sales" },
      { title: "Demand Planning Analyst", location: "Yaoundé", type: "Full-time", team: "Supply Chain" },
    ],
    csrPillars: [
      { title: "Economic opportunity", text: "Every route we open creates livelihoods — for our people and for the tens of thousands of small retailers who depend on dependable supply." },
      { title: "People & safety", text: "We invest in the training, welfare and safety of our 300+ colleagues across warehouses, fleet and field." },
      { title: "Community & education", text: "Through affordable school supplies and back-to-school programmes, we help keep classrooms stocked across Cameroon." },
      { title: "Responsible operations", text: "We work to reduce waste, optimise delivery routes and lower the footprint of our distribution network." },
    ],
    branches: [
      { role: "Headquarters & central warehouse", region: "Centre" },
      { role: "Import gateway & logistics hub", region: "Littoral" },
      { role: "Regional distribution centre", region: "West" },
      { role: "Eastern distribution hub", region: "East" },
      { role: "Highlands depot", region: "West" },
      { role: "Depot & delivery point", region: "West" },
      { role: "Northern gateway hub", region: "Adamawa" },
    ],
  },

  about: {
    breadcrumb: "Home / About",
    eyebrow: "About Henri & Frères",
    title: "A distribution company built on trust.",
    intro: "For more than three decades we have connected manufacturers to the Cameroonian consumer — combining national reach with the discipline of a modern supply-chain business.",
    missionLabel: "Our mission",
    visionLabel: "Our vision",
    vision: "To be recognised as Cameroon’s most trusted and capable distribution partner — the network global brands rely on to reach every shelf, and every shopper, in the country.",
    scaleEyebrow: "Our scale",
    scaleTitle: "Growth measured in reach and reliability",
    approachEyebrow: "Our approach",
    approachTitle: "Family roots, corporate discipline.",
    approach1: "We remain a family-founded business — and that heritage shows in how we treat partners, colleagues and customers. But the way we operate is unmistakably modern: structured warehousing, disciplined stock rotation, data-led coverage and a fleet built for velocity.",
    approach2: "It’s a combination that has earned the confidence of some of the world’s largest manufacturers, and of the thousands of retailers who depend on us to keep their shelves full.",
    valuesEyebrow: "Our values",
    valuesTitle: "The principles behind every delivery",
    valuesIntro: "Six commitments that have guided us from a single storefront to a nationwide network.",
    leadershipEyebrow: "Leadership",
    leadershipTitle: "The people steering the network",
    leadershipIntro: "Experienced leaders combining entrepreneurial heritage with operational rigour.",
    milestonesEyebrow: "Milestones",
    milestonesTitle: "Three decades of deliberate growth",
    leaders: [
      { role: "Founder", bio: "The entrepreneur whose trust with local retailers in 1993 became the foundation of a national distribution company." },
      { role: "Managing Director", bio: "Leads the company’s operations and growth strategy, scaling the network while preserving the service ethic it was built on." },
    ],
  },

  ourStory: {
    breadcrumb: "Home / Our Story",
    eyebrow: "Our Story · Since 1993",
    title: "How a single shop became a national network.",
    intro: "A story of trust, patience and relentless service — told across three decades of Cameroonian commerce.",
    s1Eyebrow: "1993 — The beginning",
    s1Quote: "It started the way most enduring businesses do — with one person, one storefront, and a reputation worth more than any balance sheet.",
    s1Body: "In 1993, Henri Tsakou Tiomela opened a modest shop in Yaoundé, trading the everyday products Cameroonian families depend on. What set the business apart was not its size but its dependability. Retailers knew that what Henri promised, Henri delivered. That trust compounded — order by order, season by season.",
    imageAlt: "Cameroonian marketplace and trade",
    s2Eyebrow: "2004 — A company takes shape",
    s2Title: "From trader to distributor.",
    s2Body: "By 2004, demand had outgrown the storefront. The business was formally incorporated as Henri & Frères SARL, and with structure came ambition. A base near the Douala port opened the door to importation and primary distribution — and the company began building the regional footprint that defines it today.",
    s2Stats: [
      { label: "Trading begins" },
      { label: "Incorporated" },
      { label: "Regional hubs today" },
      { label: "Colleagues" },
    ],
    s3Eyebrow: "Today — Part of everyday life",
    s3Body1: "Three decades on, Henri & Frères moves the brands Cameroon lives with — from global names like Unilever and Colgate to our own Henri and Two Cows labels. We employ more than 300 people, operate eight regional gateways, and serve tens of thousands of outlets from the modern supermarket to the roadside kiosk.",
    s3Body2: "The storefront has become a network. But the principle that built it — deliver on your promise, every time — has never changed.",
  },

  products: {
    breadcrumb: "Home / Products",
    eyebrow: "Our Portfolio",
    title: "Everyday products, delivered nationwide.",
    intro: "Seven categories spanning the essentials Cameroonian households and businesses rely on — carried from leading manufacturers and our own trusted brands.",
    browseEyebrow: "Browse the range",
    browseTitle: "A portfolio built around the Cameroonian basket",
    browseIntro: "Filter by category to explore representative lines. Our full assortment spans hundreds of SKUs across the modern and traditional trade.",
    byCategoryEyebrow: "By category",
    byCategoryTitle: "Seven categories, one supply chain",
    note: "Looking for a specific brand or SKU?",
  },

  brands: {
    breadcrumb: "Home / Brands",
    eyebrow: "Brands We Represent",
    title: "The brands Cameroon trusts — carried by the network that reaches it.",
    intro: "We are the chosen distribution partner for global manufacturers and regional leaders alike, and the proud owner of two trusted homegrown labels.",
    ownedEyebrow: "Our own brands",
    ownedTitle: "Made for Cameroon, by Henri & Frères",
    ownedIntro: "Beyond distribution, we build brands of our own — dependable quality at a price that works for the Cameroonian shopper.",
    distributedNote: "Distributed across all eight regional hubs",
    partnersEyebrow: "Principal partners",
    partnersTitle: "Trusted by the world’s leading manufacturers",
    partnersIntro: "A portfolio of partnerships spanning food, personal care, dairy and household — distributed with the discipline each brand demands.",
  },

  distribution: {
    breadcrumb: "Home / Distribution",
    eyebrow: "Distribution & Logistics",
    title: "The supply spine of Cameroonian commerce.",
    intro: "From the Douala port to the northern corridor, our network moves product with the speed, discipline and reach that FMCG demands.",
    capacity: [
      { label: "Regional distribution hubs" },
      { label: "Retail outlets reached" },
      { label: "Regions covered" },
      { label: "Order fulfilment rate" },
    ],
    mapEyebrow: "Network map",
    mapTitle: "Eight gateways, complete coverage.",
    mapIntro: "Each hub is positioned to serve its region efficiently — reducing lead times, protecting stock availability and bringing trusted products closer to the consumer.",
    howEyebrow: "How it works",
    howTitle: "A supply chain engineered for velocity",
    howIntro: "Four disciplined stages take a product from the port to the shopper’s basket — reliably, and at scale.",
    chain: [
      { title: "Import & sourcing", text: "Goods arrive through the Douala gateway, cleared and consolidated for onward distribution." },
      { title: "Regional warehousing", text: "Stock is received into regional warehouses with disciplined FEFO rotation and inventory control." },
      { title: "Primary & secondary delivery", text: "A modern fleet moves product from hub to depot to the point of sale, on planned routes." },
      { title: "Retail execution", text: "Field teams secure availability and visibility across modern and traditional trade." },
    ],
    fleetEyebrow: "Fleet & warehousing",
    fleetTitle: "Built to move at the speed of demand.",
    fleetBody: "Our regional warehouses and modern delivery fleet form an integrated system — one designed to keep shelves full and lead times short, even in the most demanding seasons. Ongoing investment in vehicles and storage capacity keeps our fulfilment rate above 99%.",
    fleetMetrics: [
      { label: "Fulfilment" },
      { label: "Warehouses" },
      { label: "Typical replenishment" },
    ],
  },

  services: {
    breadcrumb: "Home / Services",
    eyebrow: "What We Do",
    title: "End-to-end distribution, handled with discipline.",
    intro: "From the port to the point of sale, we manage every link in the chain — so our principals can focus on building brands while we build reach.",
    propEyebrow: "For our principals",
    propTitle: "One partner. Complete market coverage.",
    propBody: "Appointing Henri & Frères means gaining a single, accountable route to the entire Cameroonian market. We handle importation, storage, distribution and execution as one integrated service — backed by the data you need to steer performance.",
    propImageAlt: "Commercial team reviewing distribution data",
    propBullets: [
      "National reach in one agreement",
      "Modern & traditional trade",
      "Transparent sell-out reporting",
      "Dedicated key-account teams",
    ],
  },

  partners: {
    breadcrumb: "Home / Partners",
    eyebrow: "Partnerships",
    title: "Grow with the network the market trusts.",
    intro: "We build long-term partnerships that turn distribution into a measurable growth engine — for global names and homegrown brands alike.",
    logosNote: "A portfolio of trusted principals",
    whoEyebrow: "Who we partner with",
    whoTitle: "Built for every kind of partner",
    whoIntro: "Whatever your starting point, we design a route-to-market that fits your brand and your ambitions.",
    types: [
      { title: "Multinational manufacturers", text: "A turnkey route to the Cameroonian market with the coverage, compliance and reporting global brands expect." },
      { title: "Regional suppliers", text: "Access to national distribution and retail execution that would take years to build alone." },
      { title: "Retailers & wholesalers", text: "Reliable supply of trusted brands, on time and in full, across every category we carry." },
      { title: "Institutions & government", text: "Dependable bulk supply and distribution for organisations operating at scale." },
    ],
    commitEyebrow: "Our commitment",
    commitTitle: "What every partner can count on.",
    commitBody: "A partnership with Henri & Frères is a commitment to standards. Here is what we bring to the table from day one.",
    promises: [
      "National coverage across modern and traditional trade",
      "Transparent, data-led performance reporting",
      "Disciplined warehousing and stock management",
      "Dedicated commercial and key-account teams",
      "Compliance and clearing expertise at the Douala gateway",
      "Three decades of market credibility",
    ],
  },

  news: {
    breadcrumb: "Home / News",
    eyebrow: "Newsroom",
    title: "News & insights from the network.",
    intro: "Announcements, milestones and perspectives from across our nationwide distribution operation.",
    featured: "Featured",
    readStory: "Read the story",
    all: "All",
  },

  careers: {
    breadcrumb: "Home / Careers",
    eyebrow: "Careers",
    title: "Build your career where the country moves.",
    intro: "Join more than 300 colleagues who keep Cameroon’s shelves stocked — and grow with one of the country’s most trusted distribution companies.",
    cultureEyebrow: "Life at Henri & Frères",
    cultureTitle: "People are the network.",
    cultureBody: "Behind every delivery is a person who made it happen — in the warehouse, on the road, in the field and at head office. We invest in our people because they are the reason retailers and principals trust us.",
    cultureStats: [
      { label: "Colleagues" },
      { label: "Locations" },
      { label: "Years" },
    ],
    imageAlt: "Henri & Frères team at work",
    benefitsEyebrow: "Why join us",
    benefitsTitle: "What we offer",
    benefits: [
      { title: "Real growth", text: "A fast-moving business where capable people take on responsibility early and grow with the network." },
      { title: "Learning & development", text: "On-the-job training and mentoring across commercial, logistics and operations." },
      { title: "A team that supports you", text: "A collaborative culture rooted in respect, service and shared success." },
      { title: "Stability & safety", text: "The security of an established company that invests in the welfare of its people." },
    ],
    rolesEyebrow: "Open positions",
    rolesTitle: "Current opportunities",
    rolesIntro: "A selection of roles we are hiring for across the network. Don’t see the right fit? Send us a general application below.",
    applyEyebrow: "Apply",
    applyTitle: "Join the team",
    applyIntro: "Complete the form and attach your CV. We review every application.",
  },

  csr: {
    breadcrumb: "Home / Sustainability",
    eyebrow: "Sustainability & Impact",
    title: "Distribution that lifts communities.",
    intro: "Our network doesn’t just move products — it creates livelihoods, keeps shelves and classrooms stocked, and connects communities to the essentials they rely on.",
    commitEyebrow: "Our commitment",
    commitTitle: "Shared value, by design.",
    commit1: "A distribution network touches thousands of lives. Every route we open supports a small retailer; every warehouse we run employs a community; every back-to-school season we help keep children learning. We take that responsibility seriously.",
    commit2: "Our approach is practical and grounded — focused on the places where a distribution company can make a real, measurable difference.",
    imageAlt: "Community and local trade in Cameroon",
    focusEyebrow: "Our focus areas",
    focusTitle: "Four commitments that guide our impact",
    impactEyebrow: "Our footprint",
    impactTitle: "Impact you can measure",
    impact: [
      { label: "Retailers supported with dependable supply" },
      { label: "Direct jobs across the network" },
      { label: "Regional communities we operate in" },
    ],
    quote: "A country runs on its everyday essentials. Making them reliably available — everywhere, for everyone — is our contribution to Cameroon’s progress.",
    quoteBy: "Henri & Frères Leadership",
  },

  contact: {
    breadcrumb: "Home / Contact",
    eyebrow: "Contact",
    title: "Let’s talk distribution.",
    intro: "Whether you’re a manufacturer seeking national reach, a retailer placing an order, or a candidate exploring a career — our team is ready to help.",
    details: [
      { label: "Head office" },
      { label: "Phone" },
      { label: "Email" },
      { label: "Hours" },
    ],
    hoursValue: "Mon–Sat, 8:00 – 18:00 WAT",
    whatsappTitle: "Chat on WhatsApp",
    whatsappSub: "The fastest way to reach our team.",
    mapTitle: "Henri & Frères head office — Yaoundé",
    locationsTitle: "Our locations",
    locationsIntro: "Eight regional gateways keep us close to our partners and customers across Cameroon.",
  },

  forms: {
    application: {
      name: "Full name", namePh: "Your name",
      email: "Email", emailPh: "you@email.com",
      phone: "Phone",
      role: "Role", rolePh: "Select a role…", roleGeneral: "General application",
      message: "Why Henri & Frères?", messagePh: "Tell us briefly about your experience and motivation.",
      cv: "Résumé / CV", cvPh: "Upload your CV (PDF, DOCX — max 5MB)",
      consent: "I consent to Henri & Frères storing my details for recruitment purposes.",
      submit: "Submit application", submitting: "Submitting…",
      doneTitle: "Application received",
      doneBody: "Thank you for your interest in joining Henri & Frères. Our people team reviews every application and will be in touch if your profile matches an opening.",
      another: "Submit another application",
    },
    contact: {
      name: "Full name", namePh: "Your name",
      company: "Company", companyPh: "Company (optional)",
      email: "Email", emailPh: "you@email.com",
      phone: "Phone",
      type: "How can we help?", typePh: "Select an enquiry type…",
      message: "Message", messagePh: "Tell us a little about your enquiry…",
      consent: "I agree to be contacted about my enquiry and accept the privacy policy.",
      submit: "Send message", submitting: "Sending…",
      doneTitle: "Message sent",
      doneBody: "Thank you for reaching out. A member of our team will respond within one business day.",
      another: "Send another message",
      inquiries: [
        "Become a distribution partner",
        "Supply / manufacturer enquiry",
        "Retailer / wholesale order",
        "Careers",
        "Media & press",
        "General enquiry",
      ],
    },
  },

  companyProfile: {
    docLabel: "Corporate document",
    subtitle: "Company Profile · Cameroon’s distribution backbone",
    print: "Download / Print as PDF",
    overview: "Overview",
    overviewBody:
      "Henri & Frères SARL is one of Cameroon’s leading FMCG distribution and importation companies. From a single Yaoundé storefront opened in 1993, the business has grown into a nationwide distribution platform serving tens of thousands of retail outlets across the country.",
    keyFacts: "Key facts",
    facts: [
      { label: "Legal name", value: "Henri & Frères SARL" },
      { label: "Founded", value: "1993 (trading) · 2004 (incorporated)" },
      { label: "Headquarters", value: "Yaoundé, Cameroon" },
      { label: "Founder", value: "Henri Tsakou Tiomela" },
      { label: "Managing Director", value: "André Tsapi" },
      { label: "Employees", value: "300+" },
      { label: "Industry", value: "FMCG Wholesale Distribution & Importation" },
      { label: "Regional hubs", value: "8 (Yaoundé, Douala, Bafoussam, Bertoua, Dschang, Mbouda, Ngaoundéré + points)" },
    ],
    atGlance: "At a glance",
    brandsTitle: "Brands distributed",
    principalLabel: "Principal partners:",
    ownedLabel: "Owned brands:",
    categoriesTitle: "Product categories",
    networkTitle: "Distribution network",
    contactTitle: "Contact",
    rights: "All rights reserved.",
  },

  notFound: {
    title: "This route isn’t on our map.",
    body: "The page you’re looking for may have moved. Let’s get you back to familiar ground.",
    home: "Back to home",
    contact: "Contact us",
  },
};

export type Content = typeof en;
